config/routes.rb
Rails.application.routes.draw do

  get '/logout', to: 'session#destroy', as: 'logout'
  get '/dashboard', to: 'employees#dashboard', as: 'dashboard'
  get '/dashboard/:team_id/shifts/:id', to: 'employees#shift_details', as: 'shift_details'
  get '/create_admin', to: 'employees#create_admin', as: 'create_admin'

  resources :employees
  resources :teams do
    resources :shifts
  end
  resources :session, only: [:home, :create, :destroy]
  resources :requests, only: [:create, :update]
  resources :responses, only: [:update]

  root 'session#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :team_employees
  has_many :requests
  has_many :shifts
  has_many :teams, through: :team_employees
  has_many :responses
  accepts_nested_attributes_for :teams

  validates :name, presence: :true
  validates :name, uniqueness: :true

  def next_shift
    Shift.joins(:days).where('shifts.employee_id = ? AND days.value >= ?', self.id, Date.today).order('days.value ASC').limit(1).first
  end

  def get_next_shift_start_end_days
    self.next_shift.get_start_end_day_values if self.next_shift
  end

  def open_requests?
    !self.open_requests.empty?
  end

  def open_requests
    self.requests.select { |req| req.status === 'sent' }
  end

  def closed_requests?
    !self.closed_requests.empty?
  end

  def closed_requests
    self.requests.select { |req|
      req.status != 'sent' &&
      !req.shift.started?
    }
  end

  def awaiting_responses?
    !self.awaiting_responses.empty?
  end

  def awaiting_responses
    self.responses.select { |res| res.request.status === "sent" && !res.request.shift.started? && res.answer === "waiting" }
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update]
  before_action :authorized?, except: [:create_admin]
  before_action :set_teams, only: [:new, :create, :edit, :update]
  before_action :employee_authorized?, except: [:dashboard, :shift_details, :create_admin]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create_admin
    Employee.create(name:"Admin <#{random_string}>", assignable: false, admin: true)
    redirect_to root_path
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save ? (redirect_to @employee) : (render :new)
  end

  def show
  end

  def edit
  end

  def update
    @employee.update(employee_params)
    @employee.save ? (redirect_to @employee) : (render :edit)
  end

  def dashboard
    @employee = current_user
    if @employee.teams.length > 0
      @next_shift_start_end_days = @employee.get_next_shift_start_end_days
      set_dashboard_calendar
    end
  end

  def shift_details
    @shift = Shift.find_by_id(params[:id])
    @request = Request.new
    @potential_trades = @shift.get_potential_trades
  end

  private

    def employee_params
      params.require(:employee).permit(:name, :assignable, :admin, :team_ids => [])
    end

    def set_employee
      @employee = Employee.find_by_id(params[:id])
    end

    def set_teams
      @teams = Team.all
    end

    def set_dashboard_calendar
      if params[:employee]
        if !employee_params[:team_ids].blank?
          team_id = employee_params[:team_ids]
        else
          team_id = @employee.teams.first.id
        end
      else
        team_id = @employee.teams.first.id
      end
      @team = Team.find_by_id(team_id)
      team_shift_ids = @team.collect_shift_ids_by_team
      @events_by_date = Day.where(shift_id: team_shift_ids, workday: true).group_by(&:value)
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper

  def closed_swap_request_tag(request)
    if request.status === "completed"
      {msg: "COMPLETED", color: "green"}
    elsif request.all_responses_declined?
      {msg: "DECLINED", color: "red"}
    elsif request.all_responses_expired? || request.shift.started?
      {msg: "EXPIRED", color: "red"}
    else
      {msg: "CANCELED", color: "yellow darken-3"}
    end
  end

  def closed_swap_response_tag(response)
    if response.answer === "waiting"
      {msg: "WAITING", color: "grey"}
    elsif response.answer === "decline"
      {msg: "DECLINED", color: "red"}
    elsif response.answer === "accept"
      {msg: "ACCEPTED", color: "green"}
    else
      {msg: "EXPIRED", color: "red"}
    end
  end

  def active_swap_requests?(shift)
    shift.active_swap_requests?
  end

  def shift_team_curent_shift(shift)
    shift.team.current_shift
  end

  def shift_started?(shift)
    shift.started?
  end

  def responses_of_sent_request(shift)
    shift.responses_of_sent_request
  end

  def concat_response_info(response)
    response.concat_response_info
  end

  def active_swap_request(shift)
    shift.active_swap_request
  end

  def sort_employees_by_id(employees)
    employees.sort_by(&:id)
  end

  def employee_open_requests?(employee)
    employee.open_requests?
  end

  def employee_open_requests(employee)
    employee.open_requests
  end

  def employee_closed_requests?(employee)
    employee.closed_requests?
  end

  def employee_closed_requests(employee)
    employee.closed_requests
  end

  def display_req_info(instance)
    instance.display_req_info
  end

  def display_res_info(response)
    response.display_res_info
  end

  def employee_awaiting_responses?(employee)
    employee.awaiting_responses?
  end

  def employee_awaiting_responses(employee)
    employee.awaiting_responses
  end

  def employee_next_shift(employee)
    employee.next_shift
  end

  def format_next_shift_dates(day)
    day.strftime("%A, %m/%d/%Y")
  end

  def random_string
    SecureRandom.hex(8)
  end

end

app/views/employees/_form.html.erb
<div class="row" style="margin-bottom: 50px">

  <%= form_for employee do |f| %>

    <% if employee.errors.any? %>
      <div id="error_explanation">
        <h6>
          <%= pluralize(employee.errors.count, "error") %> prohibited
          this employee from being saved:
        </h6>

        <ul>
        <% employee.errors.full_messages.each do |msg| %>
          <li class="red-text"><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col s6">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="row">
      <%= f.check_box :assignable, class:"filled-in" %>
      <%= f.label :assignable, "Assignable?" %>
    </div>

    <div class="row">
      <%= f.check_box :admin, class:"filled-in" %>
      <%= f.label :admin, "Admin?" %>
    </div>

    <div class="row">
      <%= f.label :teams, "Teams" %>
      <%= f.collection_check_boxes :team_ids, teams, :id, :name do |t| %>
        <p>
          <ul style="list-style-type:none">
            <li>
              <div class="filled-in">
                <%= t.check_box(class:"filled-in") %> <%= t.label %>
              </div>
            </li>
          </ul>
        </p>
      <% end %>
    </div>

</div>

  <button class="btn-floating btn-large waves-effect waves-light tooltipped" data-position="top" data-delay="50" data-tooltip="Save" style="margin-left:1em">
      <i class="material-icons icon-white"><%= f.submit "save"%></i>
  </button>

  <% end %>

app/views/employees/dashboard.html.erb
<div class="row"></div>

<div class="row">
  <div class="col s9">
    <div class="divider"></div>
    <div class="row"></div>
      <%= render partial: "employees/dashboard_partials/next_shift", locals: {employee: @employee, next_shift_start_end_days: @next_shift_start_end_days} %>
    <div class="divider"></div>
    <div class="row"></div>
      <%= render partial: "employees/dashboard_partials/select_schedule", locals: {employee: @employee} %>
    <div class="divider"></div>
    <div class="row"></div>
      <%= render partial: "employees/dashboard_partials/schedule", locals: {team: @team, date: @date, events_by_date: @events_by_date} %>
  </div>

  <div class="col s3">
    <div class="center-align">
      <%= render partial: "employees/dashboard_partials/open_swap_req", locals: {employee: @employee} %>
    </div>
    <div class="center-align">
      <%= render partial: "employees/dashboard_partials/other_swap_req", locals: {employee: @employee} %>
    </div>
    <div class="center-align">
      <%= render partial: "employees/dashboard_partials/closed_swap_req", locals: {employee: @employee} %>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div style="margin-top: 20px; margin-bottom: 50px">
  <h4 class="center-align">Edit Employee</h4>

  <%= render partial: "form", locals: {employee: @employee, teams: @teams} %>

  <button class="btn-floating btn-large red tooltipped" data-position="top" data-delay="50" data-tooltip="Cancel" style="margin-left:1em">
    <i class="material-icons icon-white"><%= link_to "cancel", employee_path(@employee), method: :get, class: "icon-white" %></i>
  </button>
</div>

app/views/employees/index.html.erb
<h4 class="center-align">Employees</h4>

<div class="container">
    <div class="col s8">
      <table class="highlight">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Admin</th>
            <th>Assignable?</th>
          </tr>
        </thead>

        <tbody>
          <% sort_employees_by_id(@employees).each do |employee| %>
            <tr>
              <td><%= link_to employee.id, employee_path(employee), method: :get %></td>
              <td><%= employee.name %></td>
              <td>
                <% if employee.admin %>
                  <i class="material-icons small icon-green">check</i>
                <% end %>
              </td>
              <td>
                <% if employee.assignable %>
                  <i class="material-icons small icon-green">check</i>
                <% end %>
              </td>
            <tr>
          <% end %>
        </tbody>

      </table>
    </div>

</div>

<div class="right-align" style="margin: 20px 20px">
  <div className="fixed-action-btn">
    <button class="btn-floating btn-large red tooltipped" data-position="top" data-delay="50" data-tooltip="Add employee">
        <i class="material-icons icon-white"><%= link_to "add", new_employee_path, method: :get, class: "icon-white" %></i>
    </button>
  </div>
</div>

app/views/employees/new.html.erb
<div style="margin-top: 20px; margin-bottom: 50px">
  <h4 class="center-align">Create Employee</h4>

  <%= render partial: "form", locals: {employee: @employee, teams: @teams} %>

  <button class="btn-floating btn-large red tooltipped" data-position="top" data-delay="50" data-tooltip="Cancel" style="margin-left:1em">
      <i class="material-icons icon-white"><%= link_to "cancel", employees_path, method: :get, class: "icon-white" %></i>
  </button>
</div>

app/views/employees/shift_details.html.erb
<div class="row">
  <%= render partial: "shifts/details", locals: {shift: @shift, employee: true} %>
</div>

<div class="divider"></div>

<div class="row">
  <% if @shift.employee === current_user && @shift != shift_team_curent_shift(@shift) && !shift_started?(@shift) && !active_swap_requests?(@shift) && !@potential_trades.empty? %>
    <div class="row" style="margin: 2em 0">
      Request to swap this shift for one of these shifts (you may choose more than one):
    </div>
    <%= render partial: "employees/shift_details_partials/swap_req_form", locals: {shift: @shift, request: @request, potential_trades: @potential_trades} %>
  <% end %>

  <% if active_swap_requests?(@shift) %>
    <%= render partial: "employees/shift_details_partials/swap_cancellation_form", locals: {shift: @shift} %>
  <% end %>
</div>

app/views/employees/show.html.erb
<h4 class="center-align">Employee Details</h4>

<div style="margin-bottom: 20px">
  <div class="row">
    <div class="col s9">
      <p>
        id: <%= @employee.id %>
      </p>
      <p>
        Name: <%= @employee.name %>
      </p>
      <p>
        Assignable? <% if @employee.assignable %>
          <i class="material-icons small icon-green" style="vertical-align: bottom">check</i>
        <% end %>
      </p>
      <p>
        Admin?
        <% if @employee.admin %>
          <i class="material-icons small icon-green" style="vertical-align: bottom">check</i>
        <% end %>
      </p>
    </div>
    <div class="col s3" style="margin-top: 25px">
      <button class="btn-floating btn-large waves-effect waves-light tooltipped" data-position="bottom" data-delay="50" data-tooltip="Go back" style="margin-left:1em">
        <i class="material-icons icon-white"><%= button_to "arrow_back", employees_path, method: :get %></i>
      </button>
      <button class="waves-effect waves-light btn-floating btn-large red tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit employee details" style="margin-left:1em">
        <i class="material-icons icon-white"><%= button_to "edit", edit_employee_path(@employee), method: :get  %></i>
      </button>
    </div>
  </div>

  <% if !@employee.teams.empty? %>
    <div class="row">
      <div class="col s6">
        <ul class="collection with-header">
          <li class="collection-header">Teams</li>
          <% @employee.teams.each do |team| %>
              <li class="collection-item">
                <%= link_to team.name, team_path(team), method: :get, class:"collection-item" %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
      <p>
        This employee is not a member of any team.
      </p>
  <% end %>
</div>