config/routes.rb
Rails.application.routes.draw do

  get '/logout', to: 'session#destroy', as: 'logout'
  get '/dashboard', to: 'employees#dashboard', as: 'dashboard'
  get '/dashboard/:team_id/shifts/:id', to: 'employees#shift_details', as: 'shift_details'
  get '/create_admin', to: 'employees#create_admin', as: 'create_admin'

  resources :employees
  resources :teams do
    resources :shifts
  end
  resources :session, only: [:home, :create, :destroy]
  resources :requests, only: [:create, :update]
  resources :responses, only: [:update]

  root 'session#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/session.rb
class Session < ApplicationRecord
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :authorized?, except: [:home, :create]

  def home
    if !signed_in?
      @employee = Employee.new
      @employees = Employee.all
    else
      current_user_admin? ? (redirect_to teams_path) : (redirect_to dashboard_path)
    end
  end

  def create
    if !params[:employee]
      redirect_to root_path
    else
      reset_session
      @employee = Employee.find_by_id(session_params[:id])
      session[:employee_id] = @employee.id
      current_user_admin? ? (redirect_to teams_path) : (redirect_to dashboard_path)
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

    def session_params
      params.require(:employee).permit(:id)
    end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/home.html.erb
<div class="container" style="margin: 25% auto">
  <%= form_for @employee, :url => url_for(:controller => 'session', :action => 'create') do |f| %>

    <div class="row">
      <div class="col s2 offset-s1" style="padding: 10px; text-align: right; font-size: 17px">
        Login as
      </div>

      <div class="col s6">
        <%= f.collection_select :id, @employees, :id, :name %>
      </div>

      <div class="col s1" style="padding-top: 3px">
        <button type="submit" class="waves-effect waves-light btn-floating btn-medium">
          <i class="material-icons icon-white">
            <%= f.submit "navigate_next" %>
          </i>
        </button>
      </div>
    </div>
  <% end %>
</div>

<div class="center-align">
  <% if !employee_all.any? {|employee| employee.admin } %>
    <%= link_to "Create Admin", create_admin_path, method: :get %>
  <% end %>
</div>