config/routes.rb
Rails.application.routes.draw do

  get '/logout', to: 'session#destroy', as: 'logout'
  get '/dashboard', to: 'employees#dashboard', as: 'dashboard'
  get '/dashboard/:team_id/shifts/:id', to: 'employees#shift_details', as: 'shift_details'
  get '/create_admin', to: 'employees#create_admin', as: 'create_admin'

  resources :employees
  resources :teams do
    resources :shifts
  end
  resources :session, only: [:home, :create, :destroy]
  resources :requests, only: [:create, :update]
  resources :responses, only: [:update]

  root 'session#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shift.rb
require 'date'

class Shift < ApplicationRecord
  has_many :days, :dependent => :destroy
  belongs_to :team
  belongs_to :employee
  has_many :requests, :dependent => :destroy
  has_many :responses, :dependent => :destroy
  accepts_nested_attributes_for :days

  attr_accessor :assignment_method, :weeks_to_assign, :selected_date, :add_to_request, :response_shift_id

  WEEKS_ARRAY = (1..10).to_a
  WEEKS_TO_ASSIGN_MANUAL = 1

  def self.weeks_array
    WEEKS_ARRAY
  end

  def self.create_shift(args)
    assignment_method, weeks_to_assign, employee_id, team_id = args.values_at(:assignment_method, :weeks_to_assign, :employee_id, :team_id)
    team = Team.find_by_id(team_id)
    if assignment_method === 'manual'
      employee = Employee.find_by_id(employee_id)
      self.set_shift_details(WEEKS_TO_ASSIGN_MANUAL, team, employee)
    else
      self.set_shift_details(weeks_to_assign.to_i, team)
    end
  end

  def self.set_shift_details(weeks_to_assign, team, employee=nil)
    upcoming_shifts_cache = team.upcoming_shifts_days.collect { |day| day.value }
    weeks_to_assign.times do
      new_shift = Shift.new
      new_shift.team = team
      !employee ? (new_shift.employee = team.assignable_employee_array.sample) : (new_shift.employee = employee)
      dates = self.find_next_open_dates(team, upcoming_shifts_cache)
      dates.each do |key, value|
        value.each do |day|
          holiday_status = Day.holiday?(day)
          key === :on ? (workday_status = !holiday_status) : (workday_status = false)
          new_shift.days.build(value: day, holiday: holiday_status, workday: workday_status)
          upcoming_shifts_cache << day
        end
      end
      new_shift.save
    end
  end

  def self.find_next_open_dates(team, cache)
    team_workdays = team.workday_values_array
    team_start_day = team_workdays.min
    next_start_of_week = Day.date_of_next(team_start_day) - team_start_day
    finalized = false
    while !finalized do
      proposed_shift_dates = []
      off_dates = []
      day = next_start_of_week
      7.times do
        if team_workdays.include?(day.wday)
          proposed_shift_dates << day
        else
          off_dates << day
        end
        day += 1
      end

      if proposed_shift_dates.all? { |date| !cache.include?(date) }
        finalized = true
      else
        next_start_of_week += 7
      end
    end
    {:on => proposed_shift_dates.sort, :off => off_dates.sort}
  end

  def get_shift_workdays
    self.days.select{ |day| day.workday }.sort_by{ |day| day.value }
  end

  def get_shift_days
    self.days.sort_by{ |day| day.value }
  end

  def get_potential_trades
    self.team.upcoming_shifts.select { |shift| shift != self && shift.employee != self.employee }
  end

  def started?
    self.get_shift_workdays.select { |day| day.workday }.any? { |day| day.value <= Date.today }
  end

  def ended?
    self.get_shift_workdays.select { |day| day.workday }.all? { |day| day.value < Date.today }
  end

  def get_start_end_day_values
    days = self.get_shift_workdays
    start_date, end_date = days.min_by(&:value), days.max_by(&:value)
    { :start => start_date.value, :end => end_date.value }
  end

  def responses_of_sent_request
    self.requests.detect { |request| request.status === 'sent' }.responses
  end

  def active_swap_requests?
    self.requests.any? { |request| request.status === 'sent' }
  end

  def active_swap_request
    self.requests.detect { |request| request.status === 'sent' }
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :authorized?
  before_action :employee_authorized?
  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:index, :new, :create, :edit]

  def index
    @events_by_date = @team.events_by_date
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def new
    @shift = Shift.new
    @employees = @team.employees
    @weeks = Shift.weeks_array
  end

  def create
    Shift.create_shift(*shift_params)
    redirect_to team_shifts_path(@team)
  end

  def show
  end

  def edit
    @employees = @team.assignable_employee_array
  end

  def update
    @shift.update(shift_params)
    if @shift.save
      redirect_to team_shift_path(@shift)
    else
      redirect_to edit_team_shift_path(team_id: @shift.team.id, id: @shift.id)
    end
  end

  def destroy
    @shift.days.destroy
    @shift.requests.destroy
    @shift.responses.destroy
    @shift.destroy
    redirect_to team_shifts_path(params[:team_id])
  end

  private

    def shift_params
      params.require(:shift).permit(:assignment_method, :weeks_to_assign, :employee_id, :team_id, :selected_date, days_attributes: [:id, :workday])
    end

    def set_shift
      @shift = Shift.find_by_id(params[:id])
    end

    def set_team
      @team = Team.find_by_id(params[:team_id])
    end

end

app/helpers/shifts_helper.rb
require 'time'

module ShiftsHelper

  def concat_holidays(day)
    Day.get_holiday(day.value).collect {|holiday| holiday[:name]}.join(", ")
  end

  def get_shift_days(shift)
    shift.get_shift_days
  end

  def date_formatted(day)
    Day.format_date(day.value)
  end

  def get_day_of_the_week(day)
    day.get_day_of_the_week
  end

  def find_shift_by_id(id)
    Shift.find_by_id(id)
  end

end

app/views/shifts/_calendar.html.erb
  <div class="row center-align">
    <div class="col s12">
      <div class="center-align">
        <% if !dashboard %>
          <%= link_to team_shifts_path(team_id: team_id, date: date - 1.month), class: "waves-effect waves-light btn-floating btn-small", style:"margin-right: 1em" do %>
            <i class="material-icons icon-white">keyboard_arrow_left</i>
          <% end %>
        <% else %>
          <%= link_to dashboard_path(team_id: team_id, date: date - 1.month), class: "waves-effect waves-light btn-floating btn-small", style:"margin-right: 1em" do %>
            <i class="material-icons icon-white">navigate_before</i>
          <% end %>
        <% end %>
        <%= "#{date.strftime("%B")} #{date.year}" %>
        <% if !dashboard %>
          <%= link_to team_shifts_path(team_id: team_id, date: date + 1.month), class: "waves-effect waves-light btn-floating btn-small", style:"margin-left: 1em" do %>
            <i class="material-icons icon-white">navigate_next</i>
          <% end %>
        <% else %>
          <%= link_to dashboard_path(team_id: team_id, date: date + 1.month), class: "waves-effect waves-light btn-floating btn-small", style:"margin-left: 1em" do %>
            <i class="material-icons icon-white">keyboard_arrow_right</i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row center-align">
    <div class="bootstrap">
      <div class="col-md-12">
        <%= calendar date do |date| %>
          <%= date.day %>
          <% if events_by_date[date] %>
            <ul>
              <% events_by_date[date].each do |event| %>
                <li>
                  <% if !dashboard %>
                    <%= link_to find_shift_by_id(event.shift_id).employee.name, team_shift_path(team_id: find_shift_by_id(event.shift_id).team_id, id: event.shift_id), method: :get, style:"text-decoration: none"%>
                  <% else %>
                    <%= link_to find_shift_by_id(event.shift_id).employee.name, shift_details_path(team_id: find_shift_by_id(event.shift_id).team_id, id: event.shift_id), method: :get, style:"text-decoration: none"%>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/shifts/_details.html.erb
<h4 class="center-align">Shift Details</h4>

<div style="margin-bottom: 20px">
  <div class="row">
    <div class="col s8">
      <% if !employee %>
        <p>
          id: <%= shift.id %>
        </p>
      <% end %>
      <p>
        Employee: <%= link_to shift.employee.name, employee_path(shift.employee), method: :get %>
      </p>
      <p>
        Team: <%= link_to shift.team.name, team_path(shift.team), method: :get %>
      </p>
    </div>
    <div class="col s4 right-align" style="margin-top:1em">
      <button class="btn-floating btn-large waves-effect waves-light tooltipped" data-position="bottom" data-delay="50" data-tooltip="Go back" style="margin-left:1em">
        <i class="material-icons icon-white"><%= button_to "arrow_back", team_shifts_path((shift.team)), method: :get %></i>
      </button>
      <% if !employee %>
        <button class="waves-effect waves-light btn-floating btn-large red tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit shift details" style="margin-left:1em">
          <i class="material-icons icon-white"><%= button_to "edit", edit_team_shift_path(team_id: shift.team_id, id: shift.id), method: :get  %></i>
        </button>
      <% end %>
    </div>
  </div>

  <% if !shift.days.empty? %>
    <div>
      <table class="highlight" style="margin-top: 20px">
        <thead>
          <tr>
            <th class="center-align">Date</th>
            <th class="center-align">Day of the Week</th>
            <th class="center-align">Workday</th>
            <th class="center-align">Holiday</th>
          </tr>
        </thead>

        <tbody>
        <% shift.get_shift_days.each do |day| %>
          <tr>
            <td class="center-align"><%= date_formatted(day) %></td>
            <td class="center-align"><%= get_day_of_the_week(day) %></td>
            <td class="center-align">
              <% if day.workday %>
                <i class="material-icons small icon-green">check</i>
              <% end %>
            </td>
            <td class="center-align orange-text">
              <%= concat_holidays(day) %>
            </td>
          <tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>
      This shift has no days.
    </p>
  <% end %>
</div>

app/views/shifts/edit.html.erb
<h4 class="center-align">Edit Shift</h4>

<div style="margin-bottom:20px">
  <div class="row">
    <p>
      id: <%= @shift.id %>
    </p>
    </div>
  </div>
  <div class="row">
    <%= form_for @shift, :url => {:action => "update", :id => @shift} do |f| %>

      <% if @shift.errors.any? %>
        <div id="error_explanation">
          <h6>
            <%= pluralize(@shift.errors.count, "error") %> prohibited
            this user from being saved:
          </h6>

          <ul>
          <% @shift.errors.full_messages.each do |msg| %>
            <li class="red-text"><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">
        <div class="col s4">
          <%= f.label :employee_id %>
          <%= f.collection_select :employee_id, @employees, :id, :name %>
        </div>
      </div>

      <div class="row">
        <div class="col s4">
          Team: <%= @shift.team.name %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <table class="highlight" style="margin-top: 20px">
      <thead>
        <tr>
          <th class="center-align">Date</th>
          <th class="center-align">Day of the Week</th>
          <th class="center-align">Workday</th>
          <th class="center-align">Holiday</th>
        </tr>
      </thead>
      <tbody>
        <% get_shift_days(@shift).each do |day| %>
          <tr>
            <td class="center-align"><%= date_formatted(day) %></td>
            <td class="center-align">
              <%= get_day_of_the_week(day) %>
            </td>
            <td class="center-align">
              <%= f.fields_for :days, day do |day_field| %>
                <p>
                  <ul style="list-style-type:none">
                    <li>
                      <div class="row">
                        <%= day_field.check_box :workday, class: "filled-in" %>
                        <%= day_field.label :workday, "click to change" %>
                    </div>
                    </li>
                  </ul>
                </p>
              <% end %>
            </td>
            <td class="center-align">
              <div class="orange-text text-darken-3">
                <%= concat_holidays(day) %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <button class="btn-floating btn-large waves-effect waves-light tooltipped" data-position="top" data-delay="50" data-tooltip="Save" style="margin-left:1em">
    <i class="material-icons icon-white"><%= f.submit "save"%></i>
  </button>

  <% end %>

  <button class="btn-floating btn-large red tooltipped" data-position="top" data-delay="50" data-tooltip="Cancel" style="margin-left:1em">
    <i class="material-icons icon-white"><%= link_to "cancel", team_shift_path(team_id: @team.id, id: @shift.id), method: :get, class: "icon-white" %></i>
  </button>

  <button class="btn-floating btn-large orange tooltipped" data-position="top" data-delay="50" data-tooltip="Delete" style="margin-left:1em">
    <i class="material-icons icon-white"><%= link_to "delete", team_shift_path(team_id: @team.id, id: @shift.id), method: :delete, class: "icon-white" %></i>
  </button>
</div>
<div class="row"></div>

app/views/shifts/index.html.erb
<h4 class="center-align">Shifts</h4>

<p class="center-align">Team: <%= link_to @team.name, team_path(@team), method: :get %></p>

<div class="center-align">
  <div class="container">
    <%= render partial: "calendar", locals: {date: @date, events_by_date: @events_by_date, team_id: @team.id, dashboard: false} %>
  </div>
</div>

  <div class="row">
    <div class="col s12">
      <div class="right-align">
        <div className="fixed-action-btn">
          <button class="waves-effect waves-light btn-floating btn-large red tooltipped" data-position="top" data-delay="50" data-tooltip="Add shift">
            <i class="material-icons icon-white">
              <%= link_to "add", new_team_shift_path, method: :get, class: "icon-white" %>
            </i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shifts/new.html.erb
<h4 class="center-align">Create Shift</h4>

  <%= form_for @shift, :url => url_for(:controller => 'shifts', :action => 'create') do |f| %>

    <div class="container">
      <div class="row" style="padding: 50px 0">

        <div class="col s6" style="padding: 10px 0px; text-align: right">
          <%= f.radio_button :assignment_method, 'manual', :checked => true %>
          <%= f.label :assignment_method_manual, "Manually assign next open shift to" %>
        </div>

        <div class="col s6">
          <%= f.collection_select :employee_id, @employees, :id, :name, {include_blank: 'Select an employee || random', selected:""}  %>
        </div>

      </div>

      <div class="row">
        <div class="col s6" style="padding: 10px 0px; text-align: right">
          <%= f.radio_button :assignment_method, 'auto' %>
          <%= f.label :assignment_method_auto, "Randomly assign to next" %>
        </div>

        <div class="col s2">
          <%= f.select :weeks_to_assign, options_for_select(@weeks, @weeks[0]) %>
        </div>

        <div class="col s4" style="padding: 11px 0px; text-align: left">
          <label style="font-size: 14px">open shift(s)</label>
        </div>
      </div>
    </div>

    <%= f.hidden_field :team_id, value: @team.id %>

    <div class="row" style="margin: 100px 50px">
      <div class="col s12 right-align">
        <button type="submit" class="waves-effect waves-light btn">
          <%= f.submit %>
        </button>
        <button class="waves-effect waves-light btn red" style="margin-left:1em">
          <%= link_to "cancel", team_shifts_path, method: :get, class: "white-text" %>
        </button>
      </div>
    </div>

  <% end %>

app/views/shifts/show.html.erb
<%= render partial: "details", locals: {shift: @shift, employee: false} %>